//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPanel.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudPanel.App_GlobalResources.LocalizedText", typeof(LocalizedText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Company.
        /// </summary>
        internal static string Companies_AddNewCompany {
            get {
                return ResourceManager.GetString("Companies_AddNewCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Companies_Address {
            get {
                return ResourceManager.GetString("Companies_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Companies_Cancel {
            get {
                return ResourceManager.GetString("Companies_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string Companies_City {
            get {
                return ResourceManager.GetString("Companies_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        internal static string Companies_Companies {
            get {
                return ResourceManager.GetString("Companies_Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string Companies_CompanyName {
            get {
                return ResourceManager.GetString("Companies_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts Name.
        /// </summary>
        internal static string Companies_ContactsName {
            get {
                return ResourceManager.GetString("Companies_ContactsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Companies_Country {
            get {
                return ResourceManager.GetString("Companies_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Companies_Created {
            get {
                return ResourceManager.GetString("Companies_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Companies_Delete {
            get {
                return ResourceManager.GetString("Companies_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Name.
        /// </summary>
        internal static string Companies_DomainName {
            get {
                return ResourceManager.GetString("Companies_DomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies_Domains.
        /// </summary>
        internal static string Companies_Domains {
            get {
                return ResourceManager.GetString("Companies_Domains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Companies_Edit {
            get {
                return ResourceManager.GetString("Companies_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit Company.
        /// </summary>
        internal static string Companies_EditTitle {
            get {
                return ResourceManager.GetString("Companies_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string Companies_Email {
            get {
                return ResourceManager.GetString("Companies_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string Companies_Modify {
            get {
                return ResourceManager.GetString("Companies_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string Companies_State {
            get {
                return ResourceManager.GetString("Companies_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address.
        /// </summary>
        internal static string Companies_StreetAddress {
            get {
                return ResourceManager.GetString("Companies_StreetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Companies_Submit {
            get {
                return ResourceManager.GetString("Companies_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string Companies_Telephone {
            get {
                return ResourceManager.GetString("Companies_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use company name for the unique ID.
        /// </summary>
        internal static string Companies_UseUniqueID {
            get {
                return ResourceManager.GetString("Companies_UseUniqueID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        internal static string Companies_ZipCode {
            get {
                return ResourceManager.GetString("Companies_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to access your account.
        /// </summary>
        internal static string Login_LoginToAccess {
            get {
                return ResourceManager.GetString("Login_LoginToAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string Login_Signin {
            get {
                return ResourceManager.GetString("Login_Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted Domains.
        /// </summary>
        internal static string Master_AcceptedDomains {
            get {
                return ResourceManager.GetString("Master_AcceptedDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activesync Plans.
        /// </summary>
        internal static string Master_ActivesyncPlans {
            get {
                return ResourceManager.GetString("Master_ActivesyncPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        internal static string Master_Billing {
            get {
                return ResourceManager.GetString("Master_Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citrix.
        /// </summary>
        internal static string Master_Citrix {
            get {
                return ResourceManager.GetString("Master_Citrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citrix Plans.
        /// </summary>
        internal static string Master_CitrixPlans {
            get {
                return ResourceManager.GetString("Master_CitrixPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        internal static string Master_Companies {
            get {
                return ResourceManager.GetString("Master_Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Plans.
        /// </summary>
        internal static string Master_CompanyPlans {
            get {
                return ResourceManager.GetString("Master_CompanyPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string Master_Contacts {
            get {
                return ResourceManager.GetString("Master_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Master_Dashboard {
            get {
                return ResourceManager.GetString("Master_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Email.
        /// </summary>
        internal static string Master_DisableEmail {
            get {
                return ResourceManager.GetString("Master_DisableEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Groups.
        /// </summary>
        internal static string Master_DistributionGroups {
            get {
                return ResourceManager.GetString("Master_DistributionGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domains.
        /// </summary>
        internal static string Master_Domains {
            get {
                return ResourceManager.GetString("Master_Domains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Master_Email {
            get {
                return ResourceManager.GetString("Master_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Email.
        /// </summary>
        internal static string Master_EnableEmail {
            get {
                return ResourceManager.GetString("Master_EnableEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailboxes.
        /// </summary>
        internal static string Master_Mailboxes {
            get {
                return ResourceManager.GetString("Master_Mailboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailbox Plans.
        /// </summary>
        internal static string Master_MailboxPlans {
            get {
                return ResourceManager.GetString("Master_MailboxPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string Master_Overview {
            get {
                return ResourceManager.GetString("Master_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans.
        /// </summary>
        internal static string Master_Plans {
            get {
                return ResourceManager.GetString("Master_Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Folders.
        /// </summary>
        internal static string Master_PublicFolders {
            get {
                return ResourceManager.GetString("Master_PublicFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Master_Reports {
            get {
                return ResourceManager.GetString("Master_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resellers.
        /// </summary>
        internal static string Master_Resellers {
            get {
                return ResourceManager.GetString("Master_Resellers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Mailboxes.
        /// </summary>
        internal static string Master_ResourceMailboxes {
            get {
                return ResourceManager.GetString("Master_ResourceMailboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Master_Users {
            get {
                return ResourceManager.GetString("Master_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Reseller.
        /// </summary>
        internal static string Resellers_AddNewReseller {
            get {
                return ResourceManager.GetString("Resellers_AddNewReseller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Resellers_Address {
            get {
                return ResourceManager.GetString("Resellers_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Resellers_Cancel {
            get {
                return ResourceManager.GetString("Resellers_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string Resellers_City {
            get {
                return ResourceManager.GetString("Resellers_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string Resellers_CompanyName {
            get {
                return ResourceManager.GetString("Resellers_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts Name.
        /// </summary>
        internal static string Resellers_ContactName {
            get {
                return ResourceManager.GetString("Resellers_ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Resellers_Country {
            get {
                return ResourceManager.GetString("Resellers_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Resellers_Created {
            get {
                return ResourceManager.GetString("Resellers_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Resellers_Delete {
            get {
                return ResourceManager.GetString("Resellers_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Resellers_Edit {
            get {
                return ResourceManager.GetString("Resellers_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit Reseller.
        /// </summary>
        internal static string Resellers_EditTitle {
            get {
                return ResourceManager.GetString("Resellers_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string Resellers_Email {
            get {
                return ResourceManager.GetString("Resellers_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string Resellers_Modify {
            get {
                return ResourceManager.GetString("Resellers_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reseller Name.
        /// </summary>
        internal static string Resellers_Name {
            get {
                return ResourceManager.GetString("Resellers_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resellers.
        /// </summary>
        internal static string Resellers_Resellers {
            get {
                return ResourceManager.GetString("Resellers_Resellers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string Resellers_State {
            get {
                return ResourceManager.GetString("Resellers_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address.
        /// </summary>
        internal static string Resellers_StreetAddress {
            get {
                return ResourceManager.GetString("Resellers_StreetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Resellers_Submit {
            get {
                return ResourceManager.GetString("Resellers_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string Resellers_Telephone {
            get {
                return ResourceManager.GetString("Resellers_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Companies.
        /// </summary>
        internal static string Resellers_TotalCompanies {
            get {
                return ResourceManager.GetString("Resellers_TotalCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        internal static string Resellers_ZipCode {
            get {
                return ResourceManager.GetString("Resellers_ZipCode", resourceCulture);
            }
        }
    }
}
