//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LocalizedText", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Company.
        /// </summary>
        internal static string Companies_AddNewCompany {
            get {
                return ResourceManager.GetString("Companies_AddNewCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Companies_Address {
            get {
                return ResourceManager.GetString("Companies_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Companies_Cancel {
            get {
                return ResourceManager.GetString("Companies_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string Companies_City {
            get {
                return ResourceManager.GetString("Companies_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        internal static string Companies_Companies {
            get {
                return ResourceManager.GetString("Companies_Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string Companies_CompanyName {
            get {
                return ResourceManager.GetString("Companies_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts Name.
        /// </summary>
        internal static string Companies_ContactsName {
            get {
                return ResourceManager.GetString("Companies_ContactsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Companies_Country {
            get {
                return ResourceManager.GetString("Companies_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Companies_Created {
            get {
                return ResourceManager.GetString("Companies_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Companies_Delete {
            get {
                return ResourceManager.GetString("Companies_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Name.
        /// </summary>
        internal static string Companies_DomainName {
            get {
                return ResourceManager.GetString("Companies_DomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies_Domains.
        /// </summary>
        internal static string Companies_Domains {
            get {
                return ResourceManager.GetString("Companies_Domains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Companies_Edit {
            get {
                return ResourceManager.GetString("Companies_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit Company.
        /// </summary>
        internal static string Companies_EditTitle {
            get {
                return ResourceManager.GetString("Companies_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string Companies_Email {
            get {
                return ResourceManager.GetString("Companies_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string Companies_Modify {
            get {
                return ResourceManager.GetString("Companies_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string Companies_State {
            get {
                return ResourceManager.GetString("Companies_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address.
        /// </summary>
        internal static string Companies_StreetAddress {
            get {
                return ResourceManager.GetString("Companies_StreetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Companies_Submit {
            get {
                return ResourceManager.GetString("Companies_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string Companies_Telephone {
            get {
                return ResourceManager.GetString("Companies_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use company name for the unique ID.
        /// </summary>
        internal static string Companies_UseUniqueID {
            get {
                return ResourceManager.GetString("Companies_UseUniqueID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        internal static string Companies_ZipCode {
            get {
                return ResourceManager.GetString("Companies_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to access your account.
        /// </summary>
        internal static string Login_LoginToAccess {
            get {
                return ResourceManager.GetString("Login_LoginToAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string Login_Signin {
            get {
                return ResourceManager.GetString("Login_Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted Domains.
        /// </summary>
        internal static string Master_AcceptedDomains {
            get {
                return ResourceManager.GetString("Master_AcceptedDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activesync Plans.
        /// </summary>
        internal static string Master_ActivesyncPlans {
            get {
                return ResourceManager.GetString("Master_ActivesyncPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        internal static string Master_Billing {
            get {
                return ResourceManager.GetString("Master_Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citrix.
        /// </summary>
        internal static string Master_Citrix {
            get {
                return ResourceManager.GetString("Master_Citrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citrix Plans.
        /// </summary>
        internal static string Master_CitrixPlans {
            get {
                return ResourceManager.GetString("Master_CitrixPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        internal static string Master_Companies {
            get {
                return ResourceManager.GetString("Master_Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Plans.
        /// </summary>
        internal static string Master_CompanyPlans {
            get {
                return ResourceManager.GetString("Master_CompanyPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string Master_Contacts {
            get {
                return ResourceManager.GetString("Master_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Master_Dashboard {
            get {
                return ResourceManager.GetString("Master_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Email.
        /// </summary>
        internal static string Master_DisableEmail {
            get {
                return ResourceManager.GetString("Master_DisableEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Groups.
        /// </summary>
        internal static string Master_DistributionGroups {
            get {
                return ResourceManager.GetString("Master_DistributionGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domains.
        /// </summary>
        internal static string Master_Domains {
            get {
                return ResourceManager.GetString("Master_Domains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Master_Email {
            get {
                return ResourceManager.GetString("Master_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Email.
        /// </summary>
        internal static string Master_EnableEmail {
            get {
                return ResourceManager.GetString("Master_EnableEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailboxes.
        /// </summary>
        internal static string Master_Mailboxes {
            get {
                return ResourceManager.GetString("Master_Mailboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailbox Plans.
        /// </summary>
        internal static string Master_MailboxPlans {
            get {
                return ResourceManager.GetString("Master_MailboxPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string Master_Overview {
            get {
                return ResourceManager.GetString("Master_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans.
        /// </summary>
        internal static string Master_Plans {
            get {
                return ResourceManager.GetString("Master_Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Folders.
        /// </summary>
        internal static string Master_PublicFolders {
            get {
                return ResourceManager.GetString("Master_PublicFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Master_Reports {
            get {
                return ResourceManager.GetString("Master_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resellers.
        /// </summary>
        internal static string Master_Resellers {
            get {
                return ResourceManager.GetString("Master_Resellers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Mailboxes.
        /// </summary>
        internal static string Master_ResourceMailboxes {
            get {
                return ResourceManager.GetString("Master_ResourceMailboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Master_Users {
            get {
                return ResourceManager.GetString("Master_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Reseller.
        /// </summary>
        internal static string Resellers_AddNewReseller {
            get {
                return ResourceManager.GetString("Resellers_AddNewReseller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Resellers_Address {
            get {
                return ResourceManager.GetString("Resellers_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Resellers_Cancel {
            get {
                return ResourceManager.GetString("Resellers_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string Resellers_City {
            get {
                return ResourceManager.GetString("Resellers_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string Resellers_CompanyName {
            get {
                return ResourceManager.GetString("Resellers_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts Name.
        /// </summary>
        internal static string Resellers_ContactName {
            get {
                return ResourceManager.GetString("Resellers_ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Resellers_Country {
            get {
                return ResourceManager.GetString("Resellers_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Resellers_Created {
            get {
                return ResourceManager.GetString("Resellers_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Resellers_Delete {
            get {
                return ResourceManager.GetString("Resellers_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Resellers_Edit {
            get {
                return ResourceManager.GetString("Resellers_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit Reseller.
        /// </summary>
        internal static string Resellers_EditTitle {
            get {
                return ResourceManager.GetString("Resellers_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string Resellers_Email {
            get {
                return ResourceManager.GetString("Resellers_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string Resellers_Modify {
            get {
                return ResourceManager.GetString("Resellers_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reseller Name.
        /// </summary>
        internal static string Resellers_Name {
            get {
                return ResourceManager.GetString("Resellers_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resellers.
        /// </summary>
        internal static string Resellers_Resellers {
            get {
                return ResourceManager.GetString("Resellers_Resellers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string Resellers_State {
            get {
                return ResourceManager.GetString("Resellers_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address.
        /// </summary>
        internal static string Resellers_StreetAddress {
            get {
                return ResourceManager.GetString("Resellers_StreetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Resellers_Submit {
            get {
                return ResourceManager.GetString("Resellers_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string Resellers_Telephone {
            get {
                return ResourceManager.GetString("Resellers_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Companies.
        /// </summary>
        internal static string Resellers_TotalCompanies {
            get {
                return ResourceManager.GetString("Resellers_TotalCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        internal static string Resellers_ZipCode {
            get {
                return ResourceManager.GetString("Resellers_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory.
        /// </summary>
        internal static string Settings_ActiveDirectory {
            get {
                return ResourceManager.GetString("Settings_ActiveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Custom &apos;Name&apos; Attribute.
        /// </summary>
        internal static string Settings_AdvCustomNameAttrib {
            get {
                return ResourceManager.GetString("Settings_AdvCustomNameAttrib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Blocking Enabled.
        /// </summary>
        internal static string Settings_AdvIPBlockingEnabled {
            get {
                return ResourceManager.GetString("Settings_AdvIPBlockingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Blocking Failed Count.
        /// </summary>
        internal static string Settings_AdvIPBlockingFailed {
            get {
                return ResourceManager.GetString("Settings_AdvIPBlockingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Blocking Lockout In Minutes.
        /// </summary>
        internal static string Settings_AdvIPBlockingLockout {
            get {
                return ResourceManager.GetString("Settings_AdvIPBlockingLockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Allow Super Admins.
        /// </summary>
        internal static string Settings_AdvOnlySuperAdmins {
            get {
                return ResourceManager.GetString("Settings_AdvOnlySuperAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        internal static string Settings_Billing {
            get {
                return ResourceManager.GetString("Settings_Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Admins.
        /// </summary>
        internal static string Settings_BillingAdmins {
            get {
                return ResourceManager.GetString("Settings_BillingAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string Settings_CompanyName {
            get {
                return ResourceManager.GetString("Settings_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corner Logo.
        /// </summary>
        internal static string Settings_CornerLogo {
            get {
                return ResourceManager.GetString("Settings_CornerLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Currency Symbol.
        /// </summary>
        internal static string Settings_DefaultCurrencySymbol {
            get {
                return ResourceManager.GetString("Settings_DefaultCurrencySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Controller.
        /// </summary>
        internal static string Settings_DomainController {
            get {
                return ResourceManager.GetString("Settings_DomainController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Citrix Hosting.
        /// </summary>
        internal static string Settings_EnableCitrixHosting {
            get {
                return ResourceManager.GetString("Settings_EnableCitrixHosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Exchange Hosting.
        /// </summary>
        internal static string Settings_EnableExchangeHosting {
            get {
                return ResourceManager.GetString("Settings_EnableExchangeHosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Lync Hosting.
        /// </summary>
        internal static string Settings_EnableLyncHosting {
            get {
                return ResourceManager.GetString("Settings_EnableLyncHosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Reseller Accounts?.
        /// </summary>
        internal static string Settings_EnableResellerAccounts {
            get {
                return ResourceManager.GetString("Settings_EnableResellerAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Sharepoint Hosting.
        /// </summary>
        internal static string Settings_EnableSharepointHosting {
            get {
                return ResourceManager.GetString("Settings_EnableSharepointHosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Website Hosting.
        /// </summary>
        internal static string Settings_EnableWebsiteHosting {
            get {
                return ResourceManager.GetString("Settings_EnableWebsiteHosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange.
        /// </summary>
        internal static string Settings_Exchange {
            get {
                return ResourceManager.GetString("Settings_Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Type.
        /// </summary>
        internal static string Settings_ExchConnectionType {
            get {
                return ResourceManager.GetString("Settings_ExchConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Databases.
        /// </summary>
        internal static string Settings_ExchDatabases {
            get {
                return ResourceManager.GetString("Settings_ExchDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Folders Enabled.
        /// </summary>
        internal static string Settings_ExchPFEnabled {
            get {
                return ResourceManager.GetString("Settings_ExchPFEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Folder Server.
        /// </summary>
        internal static string Settings_ExchPFServer {
            get {
                return ResourceManager.GetString("Settings_ExchPFServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Server.
        /// </summary>
        internal static string Settings_ExchServer {
            get {
                return ResourceManager.GetString("Settings_ExchServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communicate using SSL.
        /// </summary>
        internal static string Settings_ExchSSLEnabled {
            get {
                return ResourceManager.GetString("Settings_ExchSSLEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Version.
        /// </summary>
        internal static string Settings_ExchVersion {
            get {
                return ResourceManager.GetString("Settings_ExchVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosting OU.
        /// </summary>
        internal static string Settings_HostingOU {
            get {
                return ResourceManager.GetString("Settings_HostingOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Logo.
        /// </summary>
        internal static string Settings_LoginLogo {
            get {
                return ResourceManager.GetString("Settings_LoginLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        internal static string Settings_Modules {
            get {
                return ResourceManager.GetString("Settings_Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Settings_Notifications {
            get {
                return ResourceManager.GetString("Settings_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Error Notifications.
        /// </summary>
        internal static string Settings_NotificationsEnable {
            get {
                return ResourceManager.GetString("Settings_NotificationsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string Settings_NotificationsFrom {
            get {
                return ResourceManager.GetString("Settings_NotificationsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Settings_NotificationsPassword {
            get {
                return ResourceManager.GetString("Settings_NotificationsPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string Settings_NotificationsPort {
            get {
                return ResourceManager.GetString("Settings_NotificationsPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string Settings_NotificationsServer {
            get {
                return ResourceManager.GetString("Settings_NotificationsServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string Settings_NotificationsTo {
            get {
                return ResourceManager.GetString("Settings_NotificationsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Settings_NotificationsUsername {
            get {
                return ResourceManager.GetString("Settings_NotificationsUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Settings_Other {
            get {
                return ResourceManager.GetString("Settings_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Settings_Password {
            get {
                return ResourceManager.GetString("Settings_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Groups.
        /// </summary>
        internal static string Settings_SecurityGroups {
            get {
                return ResourceManager.GetString("Settings_SecurityGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Settings {
            get {
                return ResourceManager.GetString("Settings_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Admins.
        /// </summary>
        internal static string Settings_SuperAdmins {
            get {
                return ResourceManager.GetString("Settings_SuperAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOMAIN\Username.
        /// </summary>
        internal static string Settings_Username {
            get {
                return ResourceManager.GetString("Settings_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users OU.
        /// </summary>
        internal static string Settings_UsersOU {
            get {
                return ResourceManager.GetString("Settings_UsersOU", resourceCulture);
            }
        }
    }
}
