//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPanel.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudPanel.App_GlobalResources.LocalizedText", typeof(LocalizedText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to access your account.
        /// </summary>
        internal static string Login_LoginToAccess {
            get {
                return ResourceManager.GetString("Login_LoginToAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string Login_Signin {
            get {
                return ResourceManager.GetString("Login_Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted Domains.
        /// </summary>
        internal static string Master_AcceptedDomains {
            get {
                return ResourceManager.GetString("Master_AcceptedDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activesync Plans.
        /// </summary>
        internal static string Master_ActivesyncPlans {
            get {
                return ResourceManager.GetString("Master_ActivesyncPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        internal static string Master_Billing {
            get {
                return ResourceManager.GetString("Master_Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citrix.
        /// </summary>
        internal static string Master_Citrix {
            get {
                return ResourceManager.GetString("Master_Citrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citrix Plans.
        /// </summary>
        internal static string Master_CitrixPlans {
            get {
                return ResourceManager.GetString("Master_CitrixPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        internal static string Master_Companies {
            get {
                return ResourceManager.GetString("Master_Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Plans.
        /// </summary>
        internal static string Master_CompanyPlans {
            get {
                return ResourceManager.GetString("Master_CompanyPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string Master_Contacts {
            get {
                return ResourceManager.GetString("Master_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Master_Dashboard {
            get {
                return ResourceManager.GetString("Master_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Email.
        /// </summary>
        internal static string Master_DisableEmail {
            get {
                return ResourceManager.GetString("Master_DisableEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Groups.
        /// </summary>
        internal static string Master_DistributionGroups {
            get {
                return ResourceManager.GetString("Master_DistributionGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domains.
        /// </summary>
        internal static string Master_Domains {
            get {
                return ResourceManager.GetString("Master_Domains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Master_Email {
            get {
                return ResourceManager.GetString("Master_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Email.
        /// </summary>
        internal static string Master_EnableEmail {
            get {
                return ResourceManager.GetString("Master_EnableEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailboxes.
        /// </summary>
        internal static string Master_Mailboxes {
            get {
                return ResourceManager.GetString("Master_Mailboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailbox Plans.
        /// </summary>
        internal static string Master_MailboxPlans {
            get {
                return ResourceManager.GetString("Master_MailboxPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string Master_Overview {
            get {
                return ResourceManager.GetString("Master_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans.
        /// </summary>
        internal static string Master_Plans {
            get {
                return ResourceManager.GetString("Master_Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Folders.
        /// </summary>
        internal static string Master_PublicFolders {
            get {
                return ResourceManager.GetString("Master_PublicFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Master_Reports {
            get {
                return ResourceManager.GetString("Master_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resellers.
        /// </summary>
        internal static string Master_Resellers {
            get {
                return ResourceManager.GetString("Master_Resellers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Mailboxes.
        /// </summary>
        internal static string Master_ResourceMailboxes {
            get {
                return ResourceManager.GetString("Master_ResourceMailboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Master_Users {
            get {
                return ResourceManager.GetString("Master_Users", resourceCulture);
            }
        }
    }
}
