// <auto-generated />
namespace CloudPanel.Modules.Persistence.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Original : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Original));
        
        string IMigrationMetadata.Id
        {
            get { return "201405092029381_Original"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
