//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPanel.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int AuditID { get; set; }
        public string CompanyCode { get; set; }
        public string Username { get; set; }
        public System.DateTime Date { get; set; }
        public int ActionID { get; set; }
        public string Variable1 { get; set; }
        public string Variable2 { get; set; }
    }
}
