//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPanel.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApiAccess> ApiAccesses { get; set; }
        public virtual DbSet<Audit> Audits { get; set; }
        public virtual DbSet<AuditLogin> AuditLogins { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyStat> CompanyStats { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<DistributionGroup> DistributionGroups { get; set; }
        public virtual DbSet<Domain> Domains { get; set; }
        public virtual DbSet<LogTable> LogTables { get; set; }
        public virtual DbSet<Plans_Citrix> Plans_Citrix { get; set; }
        public virtual DbSet<Plans_ExchangeActiveSync> Plans_ExchangeActiveSync { get; set; }
        public virtual DbSet<Plans_ExchangeMailbox> Plans_ExchangeMailbox { get; set; }
        public virtual DbSet<Plans_Organization> Plans_Organization { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<ResourceMailbox> ResourceMailboxes { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<Stats_CitrixCount> Stats_CitrixCount { get; set; }
        public virtual DbSet<Stats_ExchCount> Stats_ExchCount { get; set; }
        public virtual DbSet<Stats_UserCount> Stats_UserCount { get; set; }
        public virtual DbSet<SvcMailboxDatabaseSize> SvcMailboxDatabaseSizes { get; set; }
        public virtual DbSet<SvcMailboxSize> SvcMailboxSizes { get; set; }
        public virtual DbSet<SvcQueue> SvcQueues { get; set; }
        public virtual DbSet<SvcTask> SvcTasks { get; set; }
        public virtual DbSet<UserPermission> UserPermissions { get; set; }
        public virtual DbSet<UserPlansCitrix> UserPlansCitrices { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Plans_TerminalServices> Plans_TerminalServices { get; set; }
        public virtual DbSet<PriceOverride> PriceOverrides { get; set; }
        public virtual DbSet<UserPlan> UserPlans { get; set; }
    
        public virtual int DeleteCompany(string companyCode)
        {
            var companyCodeParameter = companyCode != null ?
                new ObjectParameter("CompanyCode", companyCode) :
                new ObjectParameter("CompanyCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteCompany", companyCodeParameter);
        }
    
        public virtual int DeleteUser(string userPrincipalName)
        {
            var userPrincipalNameParameter = userPrincipalName != null ?
                new ObjectParameter("UserPrincipalName", userPrincipalName) :
                new ObjectParameter("UserPrincipalName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteUser", userPrincipalNameParameter);
        }
    
        public virtual int DisableExchange(string companyCode)
        {
            var companyCodeParameter = companyCode != null ?
                new ObjectParameter("CompanyCode", companyCode) :
                new ObjectParameter("CompanyCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DisableExchange", companyCodeParameter);
        }
    
        public virtual int DisableMailbox(string userPrincipalName)
        {
            var userPrincipalNameParameter = userPrincipalName != null ?
                new ObjectParameter("UserPrincipalName", userPrincipalName) :
                new ObjectParameter("UserPrincipalName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DisableMailbox", userPrincipalNameParameter);
        }
    
        public virtual int UpdatePriceOverride(string companyCode, string customPrice, Nullable<int> planID, string product)
        {
            var companyCodeParameter = companyCode != null ?
                new ObjectParameter("CompanyCode", companyCode) :
                new ObjectParameter("CompanyCode", typeof(string));
    
            var customPriceParameter = customPrice != null ?
                new ObjectParameter("CustomPrice", customPrice) :
                new ObjectParameter("CustomPrice", typeof(string));
    
            var planIDParameter = planID.HasValue ?
                new ObjectParameter("PlanID", planID) :
                new ObjectParameter("PlanID", typeof(int));
    
            var productParameter = product != null ?
                new ObjectParameter("Product", product) :
                new ObjectParameter("Product", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdatePriceOverride", companyCodeParameter, customPriceParameter, planIDParameter, productParameter);
        }
    }
}
