//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPanel.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plans_Citrix
    {
        public int CitrixPlanID { get; set; }
        public string Name { get; set; }
        public string GroupName { get; set; }
        public string Description { get; set; }
        public bool IsServer { get; set; }
        public string CompanyCode { get; set; }
        public string Price { get; set; }
        public string Cost { get; set; }
        public string PictureURL { get; set; }
    }
}
