//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPanel.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SvcMailboxDatabaseSize
    {
        public int ID { get; set; }
        public string DatabaseName { get; set; }
        public string Server { get; set; }
        public string DatabaseSize { get; set; }
        public System.DateTime Retrieved { get; set; }
    }
}
