//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPanel.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPlansCitrix
    {
        public int UPCID { get; set; }
        public int UserID { get; set; }
        public int CitrixPlanID { get; set; }
    }
}
