//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPanel.Modules.Common.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    
    public partial class CPDatabase : DbContext
    {
        public CPDatabase()
            : base("name=CPDatabase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ApiAccess> ApiAccesses { get; set; }
        public DbSet<Audit> Audits { get; set; }
        public DbSet<AuditLogin> AuditLogins { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<CompanyStat> CompanyStats { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<DistributionGroup> DistributionGroups { get; set; }
        public DbSet<Domain> Domains { get; set; }
        public DbSet<LogTable> LogTables { get; set; }
        public DbSet<Plans_Citrix> Plans_Citrix { get; set; }
        public DbSet<Plans_ExchangeActiveSync> Plans_ExchangeActiveSync { get; set; }
        public DbSet<Plans_ExchangeMailbox> Plans_ExchangeMailbox { get; set; }
        public DbSet<Plans_Organization> Plans_Organization { get; set; }
        public DbSet<Plans_TerminalServices> Plans_TerminalServices { get; set; }
        public DbSet<PriceOverride> PriceOverrides { get; set; }
        public DbSet<Price> Prices { get; set; }
        public DbSet<ResourceMailbox> ResourceMailboxes { get; set; }
        public DbSet<Setting> Settings { get; set; }
        public DbSet<Stats_CitrixCount> Stats_CitrixCount { get; set; }
        public DbSet<Stats_ExchCount> Stats_ExchCount { get; set; }
        public DbSet<Stats_UserCount> Stats_UserCount { get; set; }
        public DbSet<SvcMailboxDatabaseSize> SvcMailboxDatabaseSizes { get; set; }
        public DbSet<SvcMailboxSize> SvcMailboxSizes { get; set; }
        public DbSet<SvcQueue> SvcQueues { get; set; }
        public DbSet<SvcTask> SvcTasks { get; set; }
        public DbSet<UserPermission> UserPermissions { get; set; }
        public DbSet<UserPlan> UserPlans { get; set; }
        public DbSet<UserPlansCitrix> UserPlansCitrices { get; set; }
        public DbSet<User> Users { get; set; }
    
        public virtual int DeleteUser(string userPrincipalName)
        {
            var userPrincipalNameParameter = userPrincipalName != null ?
                new ObjectParameter("UserPrincipalName", userPrincipalName) :
                new ObjectParameter("UserPrincipalName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteUser", userPrincipalNameParameter);
        }
    
        public virtual int DisableExchange(string companyCode)
        {
            var companyCodeParameter = companyCode != null ?
                new ObjectParameter("CompanyCode", companyCode) :
                new ObjectParameter("CompanyCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DisableExchange", companyCodeParameter);
        }
    }
}
