//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SharedResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string BUTTON_Cancel {
            get {
                return ResourceManager.GetString("BUTTON_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string BUTTON_Delete {
            get {
                return ResourceManager.GetString("BUTTON_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string BUTTON_Save {
            get {
                return ResourceManager.GetString("BUTTON_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string BUTTON_Submit {
            get {
                return ResourceManager.GetString("BUTTON_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string FORM_City {
            get {
                return ResourceManager.GetString("FORM_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string FORM_CompanyName {
            get {
                return ResourceManager.GetString("FORM_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string FORM_Country {
            get {
                return ResourceManager.GetString("FORM_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string FORM_Email {
            get {
                return ResourceManager.GetString("FORM_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string FORM_State {
            get {
                return ResourceManager.GetString("FORM_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address.
        /// </summary>
        internal static string FORM_StreetAddress {
            get {
                return ResourceManager.GetString("FORM_StreetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string FORM_Telephone {
            get {
                return ResourceManager.GetString("FORM_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        internal static string FORM_ZipCode {
            get {
                return ResourceManager.GetString("FORM_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activesync Plans.
        /// </summary>
        internal static string MENU_ActivesyncPlans {
            get {
                return ResourceManager.GetString("MENU_ActivesyncPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        internal static string MENU_Billing {
            get {
                return ResourceManager.GetString("MENU_Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citrix.
        /// </summary>
        internal static string MENU_Citrix {
            get {
                return ResourceManager.GetString("MENU_Citrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citrix Plans.
        /// </summary>
        internal static string MENU_CitrixPlans {
            get {
                return ResourceManager.GetString("MENU_CitrixPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        internal static string MENU_Companies {
            get {
                return ResourceManager.GetString("MENU_Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Plans.
        /// </summary>
        internal static string MENU_CompanyPlans {
            get {
                return ResourceManager.GetString("MENU_CompanyPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string MENU_Contacts {
            get {
                return ResourceManager.GetString("MENU_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string MENU_Dashboard {
            get {
                return ResourceManager.GetString("MENU_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Email.
        /// </summary>
        internal static string MENU_DisableEmail {
            get {
                return ResourceManager.GetString("MENU_DisableEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domains.
        /// </summary>
        internal static string MENU_Domains {
            get {
                return ResourceManager.GetString("MENU_Domains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string MENU_Email {
            get {
                return ResourceManager.GetString("MENU_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Email.
        /// </summary>
        internal static string MENU_EnableEmail {
            get {
                return ResourceManager.GetString("MENU_EnableEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Groups.
        /// </summary>
        internal static string MENU_Groups {
            get {
                return ResourceManager.GetString("MENU_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailbox Plans.
        /// </summary>
        internal static string MENU_MailboxPlans {
            get {
                return ResourceManager.GetString("MENU_MailboxPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string MENU_Overview {
            get {
                return ResourceManager.GetString("MENU_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans.
        /// </summary>
        internal static string MENU_Plans {
            get {
                return ResourceManager.GetString("MENU_Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Folders.
        /// </summary>
        internal static string MENU_PublicFolders {
            get {
                return ResourceManager.GetString("MENU_PublicFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string MENU_Reports {
            get {
                return ResourceManager.GetString("MENU_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resellers.
        /// </summary>
        internal static string MENU_Resellers {
            get {
                return ResourceManager.GetString("MENU_Resellers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources Mailboxes.
        /// </summary>
        internal static string MENU_ResourceMailboxes {
            get {
                return ResourceManager.GetString("MENU_ResourceMailboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string MENU_Users {
            get {
                return ResourceManager.GetString("MENU_Users", resourceCulture);
            }
        }
    }
}
