//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPanel.Modules.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int CompanyId { get; set; }
        public bool IsReseller { get; set; }
        public string ResellerCode { get; set; }
        public Nullable<int> OrgPlanID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyCode { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string PhoneNumber { get; set; }
        public string Website { get; set; }
        public string Description { get; set; }
        public string AdminName { get; set; }
        public string AdminEmail { get; set; }
        public string DistinguishedName { get; set; }
        public System.DateTime Created { get; set; }
        public bool ExchEnabled { get; set; }
        public Nullable<bool> LyncEnabled { get; set; }
        public Nullable<bool> CitrixEnabled { get; set; }
        public Nullable<int> ExchPFPlan { get; set; }
        public string Country { get; set; }
        public Nullable<bool> ExchPermFixed { get; set; }
    }
}
