//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPanel.Modules.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plans_TerminalServices
    {
        public int TSPlanID { get; set; }
        public string TSPlanName { get; set; }
        public string ResellerCode { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> MaxUserSpaceMB { get; set; }
    }
}
