//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPanel.Modules.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SvcMailboxSize
    {
        public int ID { get; set; }
        public string UserPrincipalName { get; set; }
        public string MailboxDatabase { get; set; }
        public string TotalItemSizeInKB { get; set; }
        public string TotalDeletedItemSizeInKB { get; set; }
        public int ItemCount { get; set; }
        public int DeletedItemCount { get; set; }
        public System.DateTime Retrieved { get; set; }
    }
}
