//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPanel.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogTable
    {
        public int AuditID { get; set; }
        public System.DateTime LogTime { get; set; }
        public int LogType { get; set; }
        public string CodeClass { get; set; }
        public string UserPrincipalName { get; set; }
        public string CompanyCode { get; set; }
        public string ResellerCode { get; set; }
        public string Message { get; set; }
        public string RecommendedAction { get; set; }
        public string Exception { get; set; }
    }
}
